server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/meharshitjain/student-management
          clone-on-start: true
