server:
  port: 8181

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USERS
          uri: lb://USERS
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USERS
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENTS
          uri: lb://DEPARTMENTS
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENTS
                fallbackuri: forward:/departmentServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost